image: python:3.13

stages:
 - build
 - test

# For debugging
before_script:
  - python --version
  - pip --version  
  - python -m pip install --upgrade pip

build:
  stage: build
  script:
    - python -m compileall .

test:
  stage: test
  script:
    - echo "Test temporarily disabled"
