image: python:3.13

stages:
 - build
 - test
 - docs

# For debugging
before_script:
  - python --version
  - pip --version  
  - python -m pip install --upgrade pip
  - apt-get update -y
  - apt-get install -y doxygen

build:
  stage: build
  script:
    - python -m compileall .

test:
  stage: test
  script:
    - echo "Test temporarily disabled"

build_docs:
  stage: docs
  script:
  - echo "Building Doxygen documentation..."
  - doxygen Doxyfile
  artifacts:
    paths:
      - html/